# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: platform_dev
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: platform_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./apps/backend
      target: development
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://platform_dev:dev_password@postgres:5432/platform_dev
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./apps/frontend
      target: development
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: