# infrastructure/kubernetes/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: platform-frontend
  template:
    metadata:
      labels:
        app: platform-frontend
    spec:
      containers:
      - name: frontend
        image: platform-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"