# infrastructure/kubernetes/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: platform-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: platform-frontend